import Decimal from 'decimal.js';
import type { EscapeTimePreset } from '../escape-time/presets/escapeTimePresets';

export interface DeepZoomDisplayState { deepZoomActive: boolean; precisionDigits: number; zoomDecimal: string; centerXDecimal: string; centerYDecimal: string; shaderFloat: { centerX: number; centerY: number; zoom: number }; depthLevel: string; cameraMode: 'Decimal camera'; }

export class DeepZoomCamera { /* ... */
  centerX: Decimal; centerY: Decimal; zoom: Decimal; readonly initialCenterX: Decimal; readonly initialCenterY: Decimal; readonly initialZoom: Decimal; readonly minZoom: Decimal; readonly maxZoom: Decimal; readonly precisionDigits: number;
  constructor(preset: EscapeTimePreset, precisionDigits = 64) { Decimal.set({ precision: precisionDigits, toExpNeg: -90, toExpPos: 90 }); this.precisionDigits = precisionDigits; this.centerX = new Decimal(preset.centerX); this.centerY = new Decimal(preset.centerY); this.zoom = new Decimal(preset.zoom); this.initialCenterX = new Decimal(preset.initialCenterX); this.initialCenterY = new Decimal(preset.initialCenterY); this.initialZoom = new Decimal(preset.initialZoom); this.minZoom = new Decimal(preset.minZoom); this.maxZoom = new Decimal(preset.maxZoom); }
  private screenToComplex(screenX: number, screenY: number, canvasWidth: number, canvasHeight: number) { const safeWidth = new Decimal(Math.max(canvasWidth, 1)); const safeHeight = new Decimal(Math.max(canvasHeight, 1)); const aspect = safeWidth.div(safeHeight); const nx = new Decimal(screenX).div(safeWidth).minus(0.5).times(aspect); const ny = new Decimal(0.5).minus(new Decimal(screenY).div(safeHeight)); const scale = new Decimal(3.2).div(Decimal.max(this.zoom, 1e-30)); return { x: this.centerX.plus(nx.times(scale)), y: this.centerY.plus(ny.times(scale)) }; }
  zoomAtScreenPoint(screenX:number,screenY:number,canvasWidth:number,canvasHeight:number,zoomFactor:number){const before=this.screenToComplex(screenX,screenY,canvasWidth,canvasHeight);this.zoom=Decimal.min(this.maxZoom,Decimal.max(this.minZoom,this.zoom.times(zoomFactor)));const after=this.screenToComplex(screenX,screenY,canvasWidth,canvasHeight);this.centerX=this.centerX.plus(before.x.minus(after.x));this.centerY=this.centerY.plus(before.y.minus(after.y));}
  pan(deltaX:number,deltaY:number,canvasWidth:number,canvasHeight:number){const scale=new Decimal(3.2).div(Decimal.max(this.zoom,1e-30));const aspect=new Decimal(Math.max(canvasWidth,1)).div(Math.max(canvasHeight,1));const dx=new Decimal(deltaX).div(Math.max(canvasWidth,1)).times(aspect).times(scale);const dy=new Decimal(deltaY).div(Math.max(canvasHeight,1)).times(scale);this.centerX=this.centerX.minus(dx);this.centerY=this.centerY.plus(dy);}
  reset(){this.centerX=this.initialCenterX;this.centerY=this.initialCenterY;this.zoom=this.initialZoom;}
  toShaderUniforms(){return {centerX:this.centerX.toNumber(),centerY:this.centerY.toNumber(),zoom:this.zoom.toNumber()};}
  getDisplayState():DeepZoomDisplayState{const shaderFloat=this.toShaderUniforms();const z=this.zoom;const depthLevel=z.lessThan(8)?'Nivel 1: vista general':z.lessThan(250)?'Nivel 2: acercamiento':z.lessThan(8000)?'Nivel 3: detalle':z.lessThan(300000)?'Nivel 4: profundo':'Nivel 5: muy profundo';return {deepZoomActive:true,precisionDigits:this.precisionDigits,zoomDecimal:this.zoom.toSignificantDigits(20).toString(),centerXDecimal:this.centerX.toSignificantDigits(20).toString(),centerYDecimal:this.centerY.toSignificantDigits(20).toString(),shaderFloat,depthLevel,cameraMode:'Decimal camera'};}
}
